# Generated by Django 5.1 on 2024-08-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=255)),
                ('uemail', models.EmailField(max_length=254)),
                ('unumber', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
